version: "3"
services:

  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    expose:
      - "3306"  # Port mapping format corrected
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.9
    ports:
      - "8081:80"  # Port mapping format corrected
    networks:
      - mynetwork
    environment:
      PMA_HOST: database  # Corrected PMA_HOST to match the service name
      PMA_USER: test
      PMA_PASSWORD: test
    
  node:
    build:
      context: ./app
      dockerfile: Dockerfile.node
    environment:
      DB_HOST: database  # Corrected DB_HOST to match the service name
      DB_USER: test
      DB_PASSWORD: test
      DB_NAME: mydatabase
    expose:
      - "3000"
    volumes:
      - ./my-nodejs-app:/app      
    networks:
      - mynetwork

  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile.nginx
    environment:
      REACT_APP_BACKEND_URL: http://node:3000
    ports:
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - node

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql-data:
  my-nodejs-app:

