# Use the official Nginx image as the base image
FROM nginx:latest

# Copy the build output from the client directory to the nginx web root
COPY build/ /usr/share/nginx/html

# Expose port 80
EXPOSE 80
